const LOGGED_IN = "LOGGED IN";
const USER_DETAILS = "USER DETAILS";
const LOGIN_FAILED = "USER LOGIN FAILED";
const LOGIN_SUCCESS = "USER LOGIN SUCCESS";
const FETCH_USER_DETAILS_FAILED = "FAILED TO FETCH USER DETAILS";
const LOADING = "LOADING REQUEST";
const SIGNUP_SUCCESS = "USER SIGNUP SUCCESS";
const SIGNUP_FAILED = "USER SIGNUP FAILED";
const PASSWORD_RESET_SUCCESS = "USER PASSWORD RESET SUCCESSFUL";
const PASSWORD_RESET_FAILED = "USER PASSWORD RESET FAILED";

export {
  LOGGED_IN,
  USER_DETAILS,
  LOGIN_FAILED,
  LOGIN_SUCCESS,
  FETCH_USER_DETAILS_FAILED,
  LOADING,
  SIGNUP_SUCCESS,
  SIGNUP_FAILED,
  PASSWORD_RESET_SUCCESS,
  PASSWORD_RESET_FAILED,
};
