const FETCHING_CHAT = "FETCHING USER CHATS";
const FETCHING_CHAT_FAILED = "FETCHING USER CHATS FAILED";
const FETCHING_USER_CHAT_SUCCESS = "FETCHING USER CHATS SUCCESS";
const NEW_MESSAGE = "NEW MESSAGE FROM USER";
const SENDING_MSG = "SENDING MESSAGE TO USER";
const SEND_MESSAGE_SUCCESS = "MESSAGE SENT";
const SEND_MESSAGE_FAILED = "MESSAGE NOT SENT";
const UPDATE_ACTIVE_CHAT = "SET THE ACTIVE CHAT";

export {
  FETCHING_CHAT,
  FETCHING_CHAT_FAILED,
  FETCHING_USER_CHAT_SUCCESS,
  NEW_MESSAGE,
  SENDING_MSG,
  SEND_MESSAGE_SUCCESS,
  SEND_MESSAGE_FAILED,
  UPDATE_ACTIVE_CHAT,
};
