const FETCH_PROFILE_FAILED = "FAILED TO FETCH USER PROFILE";
const FETCH_PROFILE_SUCCESS = "FETCHED USER PROFILE SUCCESSFUL";
const FETCHING_PROFILE_DETAILS = "FETCHING USER PROFILE DETAILS";

export {
  FETCH_PROFILE_FAILED,
  FETCH_PROFILE_SUCCESS,
  FETCHING_PROFILE_DETAILS,
}
