export const FETCH_PROFILE_FAILED = 'FAILED TO FETCH USER PROFILE'
export const FETCH_PROFILE_SUCCESS = 'FETCHED USER PROFILE SUCCESSFUL'
export const FETCHING_PROFILE_DETAILS = 'FETCHING USER PROFILE DETAILS'
